algoritmo "semnome"
// Função :
// Autor :
// Data : 21/06/2017
// Seção de Declarações 
var
   n1, n2, n3, n4: real
   
   soma,media: real
inicio
// Seção de Comandos 
   escreval ("Digite a primeira nota: ")
   leia(n1)
   escreval ("Digite a segunda nota: ")
   leia(n2)
   escreval ("Digite a terceira nota: ")
   leia(n3)
   escreval ("Digite a quarta nota: ")
   leia(n4)

   soma <- (n1+n2+n3+n4)
   media <- (soma/4)
   escreval ("A média final do aluno é = ", media)

fimalgoritmo
