algoritmo "semnome"
// Função :
// Autor :
// Data : 21/06/2017
// Seção de Declarações 
var
   nome : caractere
inicio
// Seção de Comandos 

   escreva ("Informe o nome da pessoa ")
   leia (nome)

   se nome = "Pedro" entao
      escreval ("Olá Pedro!!! Bem-Vindo de volta a nossa loja")
   fimse

   escreval ("Aproveite as promoções de final de ano")
   escreval ("Queima total do estoque")
fimalgoritmo
