algoritmo "semnome"
// Função :
// Autor :
// Data : 07/06/2017
// Seção de Declarações 
var
 numero1 : inteiro
 numero2 : inteiro
 resultado : inteiro
inicio
// Seção de Comandos 
   escreval ("informe o primeiro número")
   leia(numero1)
   
   escreval ("Informe o segundo número")
   leia(numero2)
   
   resultado <- numero1 + numero2
   escreva ("O resultado da soma dos número é:")
   escreva (resultado)
fimalgoritmo
