algoritmo "semnome"
// Função :
// Autor :
// Data : 14/06/2017
// Seção de Declarações 
var
   nome : caractere
   idade : inteiro
   cidade : caractere
inicio
// Seção de Comandos 
   escreval ("O comando escreva é usado para escrever na tela")
   
   //exemplo do comando escreva para mostrar o valor de uma variável
   nome <- "Augusto de Miranda"
   idade <- 18
   cidade <- "Natal"
   escreval (nome)
   escreval (idade)
   escreva (cidade)
fimalgoritmo
