algoritmo "semnome"
// Função :
// Autor :
// Data : 14/06/2017
// Seção de Declarações 
var
   nome : caractere
   idade : inteiro
   cidade : caractere
inicio
// Seção de Comandos 
   escreval ("Digite seu nome")
   leia (nome)
   escreval ("Digite sua idade")
   leia (idade)
   escreval ("Digite sua cidade")
   leia (cidade)
   
    escreva ("Os dados informado são: ", Nome, " ", Cidade, " ", Idade)

    escreval ("O nome da pessoa é: ", nome)
    escreval ("Essa pessoa mora na cidade de: ", cidade)
    escreval ("E ele está completando a idade de: ", idade)
fimalgoritmo
