algoritmo "semnome"
// Função :
// Autor :
// Data : 29/11/2010
// Seção de Declarações
var
   primeiro: real
   segundo: real
   resultado : real
inicio
   // Seção de Comandos
   escreval ("*** Esse programa vai realizar a multiplicação de 2 números ***")
   escreval ("Informe o primeiro número")
   leia(primeiro)
   escreval ("Informe o segundo número")
   leia(segundo)

   // atribui o resultado
   resultado <- primeiro * segundo

   // mostra o resultado na tela
   escreva ("O resultado da multiplicação =", resultado)
fimalgoritmo
